### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by AzaanRais** [AzaanRais/cloud-bot#4]
- [ ] complete docs.md
- [ ] add more commands
- [ ] make interface more informational
